version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./data:/app/data
      - /home/${USER}:/home/${USER}
    ports:
      - 5000:5000
      - 3001:3001
    env_file:
      - .env
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - 3000:3000
